import Header from "@/components/header/header";
import "./globals.css";
import Footer from "@/components/footer/footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col font-mono">
        <Header />
        <main className="flex-1 w-1/2 mx-auto mt-12 mb-12">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
